#!/usr/bin/env bash
set -euo pipefail
umask 077
if [[ "$(id -u)" = 0 ]]; then
  echo 'Devnet builds must run under a non-root development user' >&2
  exit 1
fi
repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$repo_root"
command -v node.exe >/dev/null
output_path="$repo_root/generated/devnet-build"
if [[ -e "$output_path" ]]; then
  echo 'Output path already exists; preserve/review or move previous artifacts before rebuilding' >&2
  exit 1
fi
build_path="$(mktemp -d -p /tmp lifecycle-kase-devnet-build.XXXXXXXX)"
cleanup() {
  if [[ "$build_path" == /tmp/lifecycle-kase-devnet-build.* && -d "$build_path" && ! -L "$build_path" && "$(stat -c '%u' "$build_path")" = "$(id -u)" ]]; then
    rm -r -- "$build_path"
  fi
}
trap cleanup EXIT
mkdir "$build_path/idl" "$build_path/types"
# The checkout's disposable localnet key is deliberately not a Devnet build identity.
# Any throwaway key generated by the build tool stays in the temporary directory.
SBF_OUT_PATH="$build_path" anchor build --ignore-keys --provider.cluster devnet --tools-version v1.57 \
  --idl "$build_path/idl" --idl-ts "$build_path/types" -- --features devnet
test -s "$build_path/lifecycle_kase.so"
node.exe "$(wslpath -w "$repo_root/scripts/check-program-identity.mjs")" "$(wslpath -w "$build_path/idl/lifecycle_kase.json")" "$(wslpath -w "$build_path/lifecycle_kase.so")"
mkdir -p "$output_path"
cp "$build_path/lifecycle_kase.so" "$build_path/idl/lifecycle_kase.json" "$output_path/"
sha256sum "$output_path/lifecycle_kase.so"
echo 'PASS isolated Devnet build; no transaction submitted or private key copied into the checkout'
